### ISSUE TITLE
Cannot set port

### ISSUE THREAD

**Issue by bbaassssiiee** [geerlingguy/ansible-role-gitlab#10]
I run a reverse proxy on ports 80&443. I would like to run GitLab behind it. Found no defaults to change for that.

**Comment by geerlingguy** [comment]
Note that the port can be configured through the existing `gitlab_external_url` variable; see the GitLab documentation here: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/nginx.md#change-the-default-port-and-the-ssl-certificate-locations

I just confirmed that this is working if I use the value `https://gitlab:8443/`—it switches from 443 to port 8443.

**Comment by geerlingguy** [comment]
Note that I'm updating the docs for the role to make this feature more explicit.
