### ISSUE TITLE
sysctl read-only, recipe 'postgresql::enable' failed

### ISSUE THREAD

**Issue by 1977er** [geerlingguy/ansible-role-gitlab#107]
I tried to install Gitlab in a (Proxmox) container and ran into a filesystem read-only issue while this role wanted to change the kernel.shmall and kernel.shmmax settings in sysctl.

sysctl settings are usually not writeable within such a container.

**Comment by ivn86** [comment]
The best way is to set parameters at host.

> Ignoring errors can have unexpected side effects on performance of your GitLab server so it is not recommended to do so.

https://docs.gitlab.com/omnibus/common_installation_problems/#failed-to-modify-kernel-parameters-with-sysctl
