### ISSUE TITLE
Copy SSL certificate from local machine missing

### ISSUE THREAD

**Issue by shumushin** [geerlingguy/ansible-role-gitlab#11]
Hello Jeff, 

It will probably be good to have an example of copying an existing SSL certificate to the machine that is managed by ansible, in case you want to secure your gitlab installation with real and non-self-generated certificate. What do you think?

**Comment by geerlingguy** [comment]
Sure! You're thinking just a documented example?

**Comment by shumushin** [comment]
Yes, or something like a task in tasks/main.yml:

```
- name: Put SSL certificate in place (key)
  copy: src=ssl.key dest={{gitlab_ssl_certificate_key}}
  when: gitlab_ssl_custom_certificate = true

- name: Put SSL certificate in place (crt)
  copy: src=ssl.pem dest={{gitlab_ssl_certificate}}
  when: gitlab_ssl_custom_certificate = true

```
Plus other stuff that is necessary for it to work.

Or even better with certificate files encrypted in vault, as SSL certificates are normally considered as sensitive information.

P.S. Great book on Ansible, thanks!

**Comment by AdrianGPrado** [comment]
Using the module copy, will look for the `ssl.key` and `ssl.pem` under `ansible-role-gitlab\files`, this presents two issues:
  - I am not sure if the folder `files` is encrypted. @geerlingguy do you know if it can be encrypted?
  - It is relatively easy to make a mistake and upload the certificates to the git repository.

I will follow the approach used in [jupyterhub-compmodels-deploy](https://github.com/rgbkrk/jupyterhub-compmodels-deploy):
  - They use [Ansible vault module](http://docs.ansible.com/ansible/playbooks_vault.html) to encrypt the file with the sensitive variables.
  - Although defined in `defaults/main.yml`, the certificates are overwritten with `vars_files`, and deployed using an encrypted file.

example:

    host: gitlab_server
    vars_files:
      - 'secrets.vault.yml'
    roles:
      - { role: geerlingguy.gitlab }

Working on it. :)

**Comment by jbrinksmeier** [comment]
How about using a letsencrypt role like https://github.com/thefinn93/ansible-letsencrypt ?
