### ISSUE TITLE
Please add support install using proxy (squid)

### ISSUE THREAD

**Issue by patsevanton** [geerlingguy/ansible-role-gitlab#113]
HI!
I try Install gitlab using this playbook using squid in Corporate NetWork.
But dont work
Please add support install using proxy (squid)
Thanks!

**Comment by TheNotary** [comment]
Are you saying the downloads for the install won't work unless you go through a corporate proxy?  If that's the case, have you tried configuring the proxy at the OS level so all connections go through the proxy?
