### ISSUE TITLE
Don't issue self signed cert by default

### ISSUE THREAD

**Issue by eRadical** [geerlingguy/ansible-role-gitlab#120]
I think this should be changed:
https://github.com/geerlingguy/ansible-role-gitlab/blob/8f4de03b02522e167d6f4964c040e24283d1833a/defaults/main.yml#L16

As GitLab now issues certs with Let's Encrypt I think this should be set to false by default.

@geerlingguy what are your thought on this?

**Comment by TheNotary** [comment]
I use lets encrypt with gitlab, but handle the creation of all my certs for all my VMs through an external process because most of my VMs are actually not exposed to the internet.

**Comment by eRadical** [comment]
Please mark this as not stale!

**Comment by geerlingguy** [comment]
See comments in #121.
