### ISSUE TITLE
gitlab config template is invalid in latest ansible version

### ISSUE THREAD

**Issue by basti1253** [geerlingguy/ansible-role-gitlab#129]
Hi,

when using the latest ansible version `gitlab-ctl reconfigure` fails. It looks like jinja is evaluating `"false"` to `False`. This is easy to fix by adding a lower pipe filter.

See https://gitlab.com/gitlab-org/omnibus-gitlab/issues/4664 and https://gitlab.com/gitlab-org/omnibus-gitlab/issues/4664#note_221509413

regards

Sebastian

**Comment by basti1253** [comment]
I overlooked that I didn't quote boolean values there like 
```yaml
gitlab_smtp_enable: false
```

commented in PR as well. As it's a configuration thingy I don't know if you want to merge the PR at all.

**Comment by geerlingguy** [comment]
I don't see the PR (maybe it was removed), but since the documentation has quoted values, and it can be a little confusing seeing the lowercase filter in the template itself when the defaults and stated values are already that way, I'd rather not add that change.
