### ISSUE TITLE
Cannot login with credentials mentioned in the README file

### ISSUE THREAD

**Issue by nop33** [geerlingguy/ansible-role-gitlab#147]
After successfully installing GitLab on a server, I tried to login using the administrator account credentials mentioned in the README file, but the login is failing... Any help on how to proceed logging in?

**Comment by electronix** [comment]
Same problem here.

Follow this instruction: https://docs.gitlab.com/ee/security/reset_root_password.html

**Comment by nop33** [comment]
After running my playbook on a new clean server, in the first visit I was asked to provide a password for the admin user. So that solved my problem.
