### ISSUE TITLE
Issue with var/main.yml

### ISSUE THREAD

**Issue by bflance** [geerlingguy/ansible-role-gitlab#15]
When i tried to run this on local machine, ansible said that it cannot find var/main.yml file for variables.

i modified it to the following to make it work:

roles/geerlingguy.gitlab/defaults/main.yml

**Comment by geerlingguy** [comment]
@bflance - I think you may be referring to the example in the README file, where it suggests you put playbook-specific variables into a playbook file you manage like `vars/main.yml`—that's just for demonstration purposes, and if you don't need to override any role variables, that's not necessary. As long as you're running a recent version of Ansible, all this role's variables files are picked up automatically.
