### ISSUE TITLE
Allow playbooks to use own gitlab.rb configuration file instead of managed file

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-gitlab#16]
Similar to how I do the managed vhosts files for Nginx and Apache roles, I'd like to allow users who need more advanced customizations to be able to do that by simply managing their own `gitlab.rb` file (instead of making the configurable parameters in this role overly complicated).

See:
- #12
- #6 

I'm thinking of using a new `gitlab_use_managed_config` variable to control whether the file will be managed or not.

**Comment by sijis** [comment]
sounds like a good idea to me :+1:

**Comment by wrockwood** [comment]
Is this a thing? I'm looking to both use omniauth and configure gitlab to use a real ssl certificate, but figuring out how to splice such things into the role is somewhat mystifying to me (primarily because I'm new to ansible). If you can point me towards documentation to get me started, that would be pretty amazing. Thanks!

**Comment by kostyrevaa** [comment]
I don't get it.
Why I can't use this role to be able to render gitlab.rb like I want.
Why do I have to have another means to render it?

**Comment by geerlingguy** [comment]
@kostyrevaa - You don't have to, but I want to provide that option. For simpler Gitlab setups, having a fully-managed simple configuration is adequate. But I don't want to have such a complicated role that has every single GitLab option available as a configurable variable, because then I'd have to keep updating the role all the time as config variables change.

Plus there will always be someone that needs a custom GitLab configuration file beyond what I could do universally in this one role.

**Comment by kostyrevaa** [comment]
> beyond what I could do universally
Aren't we using python/jinja to render template and doesn't it mean we can render pretty much every possible outcome?

**Comment by geerlingguy** [comment]
@kostyrevaa - Yes, I can do whatever I want in this role, but I'm building this role to be very generic. If you need it for a more specialized use case, then you can either fork it and do that yourself, use someone else's role, or build one bespoke; there are many ways to accomplish the same thing with Ansible, and as long as you have a secure, working server at the end of the day, it's all good :)

**Comment by jangrewe** [comment]
@geerlingguy: Maybe you can just add an option that users can define a hash that will be rendered 1:1 into the config file. That would allow you to keep using the main gitlab.rb, but users can add arbitrary other options as they see fit. Then there would be no need to use either a completely managed, or completely unmanaged config.

**Comment by plaurin84** [comment]
@zeitounator I would definitely use that :+1:

**Comment by MCyprien** [comment]
@geerlingguy I created the pull request #90 to provided parameters not present in the template using a hash like @jangrewe said. Feel free to comment the PR.

**Comment by geerlingguy** [comment]
Fixed via #89 - I like the idea of a custom template file; it's what I do for a lot of cases with other complex-to-configure apps like Nginx and Apache.
