### ISSUE TITLE
No package matching 'gitlab-ce' is available' on Ubuntu 20.04

### ISSUE THREAD

**Issue by jmcgeheeiv** [geerlingguy/ansible-role-gitlab#160]
With:
- Ubuntu 20.04
- geerlingguy.gitlab 3.0.0

I get:
```
TASK [geerlingguy.gitlab : Install GitLab] ******************************************************************************************************
fatal: [redacted IP address]: FAILED! => changed=false 
  ansible_job_id: '676724973736.20881'
  finished: 1
  msg: No package matching 'gitlab-ce' is available
```
On Ubuntu 18.04, it works. Thus this is different from #145, as gpg (GnuPG) 2.2.4 is installed by geerlingguy/gitlab 3.0.0

**Comment by StrangeletC** [comment]
May be will be useful https://forum.gitlab.com/t/unable-to-locate-package-gitlab-ee-how-to-fix/22302/9. After these steps repeat playbook and all work fine on Ubuntu Server 22.04
