### ISSUE TITLE
Package gitlab-ce not availabe (Ubuntu 15.04 server)

### ISSUE THREAD

**Issue by maschmann** [geerlingguy/ansible-role-gitlab#18]
When trying to run the role, follwing task is failing:

```
TASK: [geerlingguy.gitlab | Install GitLab] *********************************** 
failed: [myhost.de] => {"failed": true}
msg: No package matching 'gitlab-ce' is available
```
When looking at 

```
- name: Install GitLab
  apt: "name=gitlab-ce state=installed"
  when: (gitlab_file.stat.exists == false) and (ansible_os_family == 'Debian')
```
I first thought it might be a missing apt-get update, but checking the apt repos and actually doing an apt-get update on the server showed me:

```
Hit https://packages.gitlab.com vivid InRelease
Hit http://security.ubuntu.com vivid-security/universe Translation-en
Hit https://packages.gitlab.com vivid/main Sources                   
Hit https://packages.gitlab.com vivid/main amd64 Packages
Hit https://packages.gitlab.com vivid/main i386 Packages
Get:1 https://packages.gitlab.com vivid/main Translation-en
Get:2 https://packages.gitlab.com vivid/main Translation-en [162 B]
Get:3 https://packages.gitlab.com vivid/main Translation-en [162 B]
Get:4 https://packages.gitlab.com vivid/main Translation-en [162 B]
Get:5 https://packages.gitlab.com vivid/main Translation-en [162 B]
Ign https://packages.gitlab.com vivid/main Translation-en
Reading package lists... Done 
```
Any idea what might cause this?

**Comment by geerlingguy** [comment]
@maschmann - Unfortunately, I don't think GitLab's repositories support 15.04 yet, only the LTS releases. I may need to update this role to specify only LTS releases in the meta info.yml file.

**Comment by maschmann** [comment]
Ok, thank you for the research! :+1:

**Comment by foulowl** [comment]
I'm having the same issue on Debian 8.

**Comment by 030** [comment]
```
FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'gitlab-ce' is available"}
```

occurs on Ubuntu 16.04 LTS as well

**Comment by 030** [comment]
@geerlingguy Regarding:

```
@maschmann - Unfortunately, I don't think GitLab's repositories support 15.04 yet, only the LTS releases. I may need to update this role to specify only LTS releases in the meta info.yml file.
```

I was able to install gitlab on [Ubuntu 16.04](https://about.gitlab.com/downloads/#ubuntu1604) yesterday.

**Comment by geerlingguy** [comment]
It looks like there are releases for the following:

https://packages.gitlab.com/gitlab/gitlab-ce?filter=debs

**Comment by geerlingguy** [comment]
@030 - Was this using the latest version of the role (2.0.0)? If so, it's using a slightly improved installation technique—this particular issue might not be a problem anymore, as GitLab's install uses the official repo setup script now, which should work with all available releases (and not just a few that were hardcoded).

**Comment by geerlingguy** [comment]
Closing this issue, as it seems GitLab only officially supports LTS releases of Ubuntu, and current stable Debian releases (see this list for all the available builds: https://packages.gitlab.com/gitlab/gitlab-ce?filter=debs).
