### ISSUE TITLE
Debian 11 - No package matching 'gitlab-ce' is available" 

### ISSUE THREAD

**Issue by xmoulin** [geerlingguy/ansible-role-gitlab#190]
Trying the default playbook over a Debian 11. I got the error:
`
TASK [geerlingguy.gitlab : Install GitLab] *******************************************************************************************************************************************************
fatal: [gitlab01]: FAILED! => {"ansible_job_id": "960307910863.25892", "changed": false, "finished": 1, "msg": "No package matching 'gitlab-ce' is available"}
`

I try the same script over Debian 10, just to try, and it's work fine...

**Comment by lotusnoir** [comment]
Hello,
i just got the same error

The role download and run a bash script https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
Unfortunately there is no repo for debian11 yet, you need to edit this file and change bullseye by buster to install gitlab-ce

```
# cat /etc/apt/sources.list.d/gitlab_gitlab-ce.list 
# this file was generated by packages.gitlab.com for
# the repository at https://packages.gitlab.com/gitlab/gitlab-ce

deb https://packages.gitlab.com/gitlab/gitlab-ce/debian/ bullseye main
deb-src https://packages.gitlab.com/gitlab/gitlab-ce/debian/ bullseye main
```

You can then replay the playbook.
Donno if @geerlingguy still maintain this repo, but a quick fix could be a little sed on the repo.list file before package install when os release is bullseye.

**Comment by WimpyMan** [comment]
Hi guys,

I just did a fugly workaround that seems to work alright :)

https://github.com/WimpyMan/ansible-role-gitlab/commit/56b672383172565ce2a641c5d9c8b16cb82cc5aa
