### ISSUE TITLE
Installation of GitLab package can timeout

### ISSUE THREAD

**Issue by AdamGoldsmith** [geerlingguy/ansible-role-gitlab#199]
While testing GitLab installations via automated deployments, I noticed that on occasion the installation of GitLab software package can potentially timeout. The package is approx 1Gb at time of writing, so I suggest increasing the async timeout for this particular task (currently set to 300 [5 mins]). I will submit a PR for this suggestion.

**Comment by artybdrlt** [comment]
Hello, we are having the same issue here! Is this issue going to be addressed soon or not?

**Comment by BrutalBirdie** [comment]
can be adjusted with PR #200

**Comment by artybdrlt** [comment]
> can be adjusted with PR #200

That's true. Me and my team have made a fork of this role specifically to fix this issue. Would be nice if your PR was accepted.

**Comment by MrFr33man123** [comment]
I had the same Problem. doubled the timeout. Works flawless now.

**Comment by NormanJS** [comment]
Not stale
