### ISSUE TITLE
Issue running the GitLab provided install script on a CIS hardened Ubuntu Pro install

### ISSUE THREAD

**Issue by ianburrowes** [geerlingguy/ansible-role-gitlab#202]
Hi Jeff,

After applying the CIS hardening scripts to Ubuntu Pro the default umask changes to user read only (instead of read all).  As a result, the GitLab provided install script adds the GitLab PGP key for the apt repository with insufficient permissions.  To run the script successfully you need to ensure the umask is all read before the script runs.  Patch incoming!

**Comment by philchristensen** [comment]
Had the same issue on an Ubuntu AMI from the CIS foundation, was fixed by @ianburrowes PR. Thanks bud!
