### ISSUE TITLE
error running role 'iteritems' attribute missing

### ISSUE THREAD

**Issue by karlroberts** [geerlingguy/ansible-role-gitlab#21]
Hi,

I tried using this but had the following error installing the Gitlab repository.
Not sure what to so to fix this. as quite new to ansible.

Help is appreciated.

Cheers

KArl

 _______________________________________________________
< TASK [geerlingguy.gitlab : Install GitLab repository] >
 -------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

<52.64.147.103> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<52.64.147.103> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/robertk/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=22 -o IdentityFile="/home/robertk/.ssh/avo-infra.pem" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 52.64.147.103 (umask 22 && mkdir -p "$HOME/.ansible/tmp/ansible-tmp-1442204634.57-60423092737780" && echo "$HOME/.ansible/tmp/ansible-tmp-1442204634.57-60423092737780")
<52.64.147.103> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<52.64.147.103> PUT /tmp/tmpebonCK TO /home/ubuntu/.ansible/tmp/ansible-tmp-1442204634.57-60423092737780/command
<52.64.147.103> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<52.64.147.103> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/robertk/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=22 -o IdentityFile="/home/robertk/.ssh/avo-infra.pem" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 52.64.147.103 /bin/sh -c 'sudo -H -n -S -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-ccwwxkzhzmbeaewuovlcxjtfkdvqgecz; LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1442204634.57-60423092737780/command; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1442204634.57-60423092737780/" > /dev/null 2>&1'"'"''
fatal: [52.64.147.103]: FAILED! => {"changed": false, "failed": true, "msg": "BECOME-SUCCESS-ccwwxkzhzmbeaewuovlcxjtfkdvqgecz\r\nTraceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1442204634.57-60423092737780/command\", line 1914, in <module>\r\n    main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1442204634.57-60423092737780/command\", line 91, in main\r\n    module = CommandModule(argument_spec=dict())\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1442204634.57-60423092737780/command\", line 544, in __init__\r\n    self._check_for_check_mode()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1442204634.57-60423092737780/command\", line 1080, in _check_for_check_mode\r\n    for (k,v) in self.params.iteritems():\r\nAttributeError: 'tuple' object has no attribute 'iteritems'\r\nOpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014\r\ndebug1: Reading configuration data /home/robertk/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 20769\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to 52.64.147.103 closed.\r\n", "parsed": false}
 ____________

**Comment by geerlingguy** [comment]
You're issue sounds similar to https://github.com/ansible/ansible/issues/11889, and possibly http://stackoverflow.com/a/32235213/100134 — do you have Ansible installed via a git clone? If so, make sure you update all the submodules too.

**Comment by karlroberts** [comment]
OK it looks like the same issue... I picked a stable tag then ran the submodule stuff and ansible worked:- ie I did.
   
    git clone https://github.com/ansible/ansible.git
    cd ansible
    git fetch origin +refs/tags/v1.9.3-1:v1.9.3-1
    git co v1.9.3-1
    git submodule update --init --recursive
    . ./hacking/env-setup

from then on running ansible with the ansible-role-gitlab worked.

Thanks

**Comment by geerlingguy** [comment]
Great! Glad I could help.
