### ISSUE TITLE
Error when launching playbook

### ISSUE THREAD

**Issue by vldanch** [geerlingguy/ansible-role-gitlab#213]
Run:
```
ansible-playbook -i inventory/yandex/infra/hosts playbooks/gitlab.yml
```
Error:
`fatal: [gitlab-infra]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible_os_family' is undefined\n\nThe error appears to be in '/home/user/Desktop/projects/infra/base-automation/roles/ansible-role-gitlab/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Include OS-specific variables.\n  ^ here\n"}`

**Comment by NormanJS** [comment]
Are you gathering facts with your playbook? Make sure you didn't disable fact gathering
