### ISSUE TITLE
Add a swap partition present check

### ISSUE THREAD

**Issue by axi** [geerlingguy/ansible-role-gitlab#28]
As it's a recommended practice, it could be nice to add a small check on the existence of a swap partition, just to warn users... [https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/install/requirements.md](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/install/requirements.md).
Thanks anyway for this role

**Comment by geerlingguy** [comment]
I'd rather not add that as part of this role—it might be more suitable in it's own 'setup' role or a 'swap' role. That's something that's more a systemwide setting (similar to ssh setup, memory, disk mounts, etc.) that shouldn't be managed through a particular application's configuration.
