### ISSUE TITLE
Unify `yum` & `apt` Ansible modules

### ISSUE THREAD

**Issue by AdrianGPrado** [geerlingguy/ansible-role-gitlab#37]
I've noticed that there is code repeated just with the intention of having OS differentiation.

    - name: Install GitLab repository (RedHat)
      command: bash /tmp/gitlab_install_repository.sh
      when: (gitlab_file.stat.exists == false) and (ansible_os_family == 'RedHat')

    - name: Install GitLab (RedHat)
      yum: "name=gitlab-ce state=installed"
      when: (gitlab_file.stat.exists == false) and (ansible_os_family == 'RedHat')

     ...

    - name: Install GitLab repository
      command: bash /tmp/gitlab_install_repository.sh
      when: (gitlab_file.stat.exists == false) and (ansible_os_family == 'Debian')

    - name: Install GitLab
      apt: "name=gitlab-ce state=installed"
      when: (gitlab_file.stat.exists == false) and (ansible_os_family == 'Debian')

The only difference is the usage of the modules `yum` or `apt`. Ansible has a generic package manager [`package`](http://docs.ansible.com/ansible/package_module.html) which is useful in this situation, making the playbook shorter and OS agnostic (at least between 'Debian' and 'RedHat' families)

I will open a PR.

BTW: Thanks for taking the time writing [Ansible for DevOps](https://leanpub.com/ansible-for-devops) it's been really useful.

**Comment by geerlingguy** [comment]
+1 - left a comment in the PR; I'll definitely merge after those two tweaks are made. Makes this role much less obtuse!

**Comment by geerlingguy** [comment]
Merged, thanks!
