### ISSUE TITLE
As a user of this role I would like to see that runners could be created on Centos

### ISSUE THREAD

**Issue by 030** [geerlingguy/ansible-role-gitlab#41]
https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/blob/master/docs/install/linux-repository.md

**Comment by geerlingguy** [comment]
@030 - For this and #40, I'd rather leave runner setup/config to a separate role. Right now this role is focused primarily on single server or primary GitLab instance installation; I think runners would be better served using a separate role, e.g. `gitlab-runner` or something like that (unless you can think of a way to make this role's architecture simple but still support runner installs).

Having a separate role would make it easier to do runner-specific tasks like Docker setup too.
