### ISSUE TITLE
Allow end users to specify a version of gitlab

### ISSUE THREAD

**Issue by rodfmarin** [geerlingguy/ansible-role-gitlab#56]
Great Ansible Role, thank you.

One request, is it possible to allow the end user to provide a specific version of gitlab to install?
It could work in its current form by supplying the correct package-version string in 'gitlab_edition' but that variable is used in vars to construct the path to the installer script (which breaks when you try to provide a version).

Thanks!

**Comment by robbintt** [comment]
I tested the new gitlab_version variable today and it worked.

**Comment by To1ne** [comment]
>I tested the new gitlab_version variable today and it worked. 

Yes. This issue can be closed.

**Comment by bbaassssiiee** [comment]
Does it support updating the gitlab instance?
