### ISSUE TITLE
HTTP only not working

### ISSUE THREAD

**Issue by Chrisissorry** [geerlingguy/ansible-role-gitlab#58]
I try to use AWS ELB SSL termination and therefore run gitlab http only. The following vars do not work:

```
    gitlab_external_url: "http://gitlab.example.com"
    gitlab_redirect_http_to_https: "false"
    gitlab_nginx_listen_port: 80
    gitlab_nginx_listen_https: "false"
```

nginx throws a 400 with "The plain HTTP request was sent to HTTPS port".

**Comment by Chrisissorry** [comment]
After several hours of running playbooks back and forth I just discovered that using `gitlab_external_url:"http://gitlab.example.com"` does the trick -_- 

Thanks for sharing this great role. Please close this issue. Sorry for the inconvenience.

**Comment by geerlingguy** [comment]
No problem, thanks for posting the solution for the benefit of Google searches in the future!
