### ISSUE TITLE
Running as Root? Missing `become` lines?

### ISSUE THREAD

**Issue by jpartain89** [geerlingguy/ansible-role-gitlab#60]
So, I just attempted to run this on my Raspberry Pi 3, and it errored out on `Install GitLab repository`, and whilst parsing through the role, I noticed that the main GitLab script is not being called through any type of `become` options. And, your documentation does not specify including `become: True` in our play for your role. 

Not sure if this was an omission error or what, but I just ran the script on my own, first just as `bash <script>` and it failed the same, 

```
Detected operating system as raspbian/stretch.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/gitlab_gitlab-ce.list..../gitlab_install_repository.sh: line 115: /etc/apt/sources.list.d/gitlab_gitlab-ce.list: Permission denied

Unable to run:
    curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/config_file.list?os=raspbian&dist=stretch&source=script

Double check your curl installation and try again.
```

Once I ran with `sudo`, it completed without error.

**Comment by robbintt** [comment]
The `become` issue either comes from running a repository locally that's intended for remote use or from running with ansible 1.9.1 when you should be using ansible 2+. I've just got a moment now so I thought I would hop in and say this. If you reply I can take a deeper look.

**Comment by rebmal** [comment]
I'm trying to install this on a Centos 7.3  VMware server, with a user with sudo rights
I'm getting the same issues as jpartain89. Inserting 'become: true' in yaml file solved the installation problem. Curl is installed, but of course /etc/yum.repos.d is not writeble for a "normal" user. 
Error:
TASK [gitlab : Install GitLab repository] *********************************************************************
fatal: [gitlab.rutten.lan]: FAILED! => {"changed": true, "cmd": ["bash", "/tmp/gitlab_install_repository.sh"], "delta": "0:00:00.019567", "end": "2018-01-15 21:48:29.570811", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2018-01-15 21:48:29.551244", "stderr": "/tmp/gitlab_install_repository.sh: line 146: /etc/yum.repos.d/gitlab_gitlab-ce.repo: Permission denied\nrm: cannot remove ‘/etc/yum.repos.d/gitlab_gitlab-ce.repo’: Permission denied", "stderr_lines": ["/tmp/gitlab_install_repository.sh: line 146: /etc/yum.repos.d/gitlab_gitlab-ce.repo: Permission denied", "rm: cannot remove ‘/etc/yum.repos.d/gitlab_gitlab-ce.repo’: Permission denied"], "stdout": "Detected operating system as centos/7.\nChecking for curl...\nDetected curl...\nDownloading repository file: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/config_file.repo?os=centos&dist=7&source=script\n\nUnable to run: \n    curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/config_file.repo?os=centos&dist=7&source=script\n\nDouble check your curl installation and try again.", "stdout_lines": ["Detected operating system as centos/7.", "Checking for curl...", "Detected curl...", "Downloading repository file: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/config_file.repo?os=centos&dist=7&source=script", "", "Unable to run: ", "    curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/config_file.repo?os=centos&dist=7&source=script", "", "Double check your curl installation and try again."]}
        to retry, use: --limit @/home/license/gitlab.retry

PLAY RECAP ****************************************************************************************************
gitlab.rutten.lan          : ok=6    changed=0    unreachable=0    failed=1

**Comment by finalcut** [comment]
I just had the same issue on centos7  from one vagrant vm (virtual box) to another.

I am running ansible 2.4.2.0 and had to add become:true to my playbook:

```yaml
- hosts: 10.0.2.15
  vars_files:
    - vars/main.yml
  become: true
  roles:
    - { role: geerlingguy.gitlab }
```

If I remove the `become :true` it fails on the curl with permission denied just like the prior comments.
