### ISSUE TITLE
Can't install on RedHat 7.2

### ISSUE THREAD

**Issue by doronshai** [geerlingguy/ansible-role-gitlab#61]
Great Role! unfortunately I am stuck on this step:
> TASK [gitlab : Reconfigure GitLab (first run).] ********************************

even after restarting it is get stuck, and one time it managed to "finish" but the installation was corrupted and i saw messages like `[execute] fail: redis: runsv not running` when i tried to execute `/opt/gitlab/bin/gitlab-ctl start`

tried to run `/opt/gitlab/bin/gitlab-ctl tail` to see what is going on but all i see there is 

> ==> /var/log/gitlab/gitlab-rails/production.log <==
> ** [Raven] Raven 2.0.2 configured not to capture errors.
> 
> ==> /var/log/gitlab/gitlab-shell/gitlab-shell.log <==
> Logfile created on 2017-03-30 14:26:07 +0300 by logger.rb/56438

Do you have any suggestions how to tackle it?

**Comment by geerlingguy** [comment]
@doronshai - Unfortunately I haven't had as much time lately to work on this role; I know I had tested it manually on CentOS 7 in the past, but not recently—the automated test only runs on Travis' default OS (I think Ubuntu 14.04 right now—https://github.com/geerlingguy/ansible-role-gitlab/blob/master/.travis.yml), so my automated tests aren't adequately covering all the supported OSes, either :(

**Comment by geerlingguy** [comment]
See related: #83

**Comment by geerlingguy** [comment]
@doronshai - I just committed a few fixes that I _think_ should take care of things, when using CentOS 7. Closing this issue as I think the reconfigure problems should be solved, but feel free to open another if you find any other issues.
