### ISSUE TITLE
Upgrade/Update documentation mention

### ISSUE THREAD

**Issue by robbintt** [geerlingguy/ansible-role-gitlab#62]
It would be great to have a section in the readme on upgrading. It isn't immediately clear to me if the script will upgrade gitlab.  I am not experienced with gitlab but I did read that the ppa will upgrade gitlab.  I'll take a more thorough look later and maybe submit a patch. This is an enhancement.

**Comment by geerlingguy** [comment]
I personally haven't tried an upgrade of an existing GitLab instance (I've only built and rebuilt servers on newer versions, migrating the old repos...). But if someone wants to submit any docs in a PR, that would be great. I imagine with the way things are set up, GitLab's own update mechanisms should work okay if you set the `state` to `latest` here: https://github.com/geerlingguy/ansible-role-gitlab/blob/master/tasks/main.yml#L31-L33

But that would necessitate the 'state' would be a variable that defaults to `installed` but could be set to `latest` in a playbook to upgrade from the package.

**Comment by robbintt** [comment]
I ran this playbook as general maintenance and it upgraded our gitlab server. I'm not sure if this'll always happen though.  I don't know if that's intended behavior but it worked.

**Comment by robbintt** [comment]
I did this again today and it worked.  I haven't really reviewed every line of code, but am happy with the outcome. If the role is idempotent, it makes sense that this is working, because gitlab says you just update by updating through apt anyways.

**Comment by geerlingguy** [comment]
Awesome!

**Comment by fourstepper** [comment]
Sorry to wake up an old topic
@geerlingguy you mentioned just moving the repositories manually between the servers post-install

Would the steps mentioned in this guide accomplish this?
https://docs.gitlab.com/ee/administration/operations/moving_repositories.html

Thank you!
