### ISSUE TITLE
Use blocks in gitlab configuration template for easier customization

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-gitlab#67]
See my Nginx role for an example: https://github.com/geerlingguy/ansible-role-nginx/blob/master/templates/vhost.j2

Basically, this would allow people to override certain sections of the gitlab config file, and I wouldn't need to manage dozens of PRs requesting one or two additions to the file (making the file and settings in general overwhelming for the 80% use case).

**Comment by eRadical** [comment]
Hi Jeff,

Care to spare a general idea about how you see this... as I would like to give it a shot!

**Comment by eRadical** [comment]
I'll give it a shot in the following weeks!

**Comment by eRadical** [comment]
Mark as not stale!

**Comment by geerlingguy** [comment]
I think instead the two customization mechanisms now available ('extra config' as of https://github.com/geerlingguy/ansible-role-gitlab/commit/09ddc7a213e4922d0a69c05941ee8236e48fbce3, and the `gitlab_config_template` option) are better than adding blocks as I originally thought in this post.
