### ISSUE TITLE
Cannot Add LDAP groups

### ISSUE THREAD

**Issue by internetrush1** [geerlingguy/ansible-role-gitlab#69]
LDAP config is incomplete, cannot add LDAP groups to groups / projects.

**Comment by madeinoz67** [comment]
pretty sure LDAP groups is only supported on the paid enterprise edition  https://docs.gitlab.com/ee/administration/auth/ldap-ee.html

**Comment by madeinoz67** [comment]
yes I do as well, works very well with our windows domain, however my understanding is that LDAP groups appear to be only supported on the EE editions
