### ISSUE TITLE
Handler 'restart gitlab' ignores error

### ISSUE THREAD

**Issue by bradfirj** [geerlingguy/ansible-role-gitlab#8]
The `failed_when: false` line in the reconfigure handler is suppressing all errors in the `gitlab-ctl reconfigure` process. This isn't something that should be allowed to fail silently so I assume this was added for testing purposes and forgotten about?

I ran into this while drastically expanding the gitlab.rb.j2 template, and going back after adding 20 or 30 options only to discover that all my passing tests had in fact been failing.

With an intentionally malformed template file, here's the result of running the handler with the existing code:
```
NOTIFIED: [ansible-role-gitlab | restart gitlab] ****************************** 
changed: [172.16.6.189] => {"changed": true, "cmd": ["gitlab-ctl", "reconfigure"], "delta": "0:00:04.656031", "end": "2015-03-01 14:38:38.925464", "failed": false, "failed_when_result": false, "rc": 1, "start": "2015-03-01 14:38:34.269433", "stderr":  ...... snipped ..... ", "stdout": .....snipped.....", "warnings": []}
```
Without including the large amount of failure text in stdout, it's clear that when the return code is non-zero the role shouldn't be marking the step as changed successfully.

If there was a good reason for suppressing any warnings from gitlab-ctl please ignore.

**Comment by kostyrevaa** [comment]
Any comments on this one?

**Comment by geerlingguy** [comment]
I'll be testing out the PR soon.

**Comment by kostyrevaa** [comment]
thanks!
